name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  base:
    runs-on: ubuntu-20.04
    steps:
      - name: Determine effective user and group
        id: effective-user
        run: |
          echo "::set-output name=uid::$(id -u)"
          echo "::set-output name=gid::$(id -g)"

      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # renovate: tag=v1.6.0

      - name: Reload Docker buildx cache
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # renovate: tag=v2.1.6
        with:
          path: /tmp/.buildx-base-cache
          key: ${{ runner.os }}-buildx-base-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-base-
            ${{ runner.os }}-buildx-

      # Build "base" in order to load its image into Docker from the buildx
      # cache, so that the update script can then be run upon it.
      - name: Build base
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229 # renovate: tag=v2.7.0
        with:
          context: .devcontainer
          build-args: |
            USER_UID=${{ steps.effective-user.outputs.uid }}
            USER_GID=${{ steps.effective-user.outputs.gid }}
          target: base
          tags: base
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-base-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-base-cache-new
          load: true

      # Run the update script on pull requests and pushes to main in order to
      # confirm that it has not been broken; only `schedule` events will use the
      # results (opening a PR, if there are updates).
      - name: Determine Updates
        run: docker run -v ${{ github.workspace }}:/workspace base /workspace/.devcontainer/update.sh

      - name: Update cache
        run: |
          rm -rf /tmp/.buildx-base-cache
          mv /tmp/.buildx-base-cache{-new,}

      - name: Generate GitHub token
        id: generate-token
        if: ${{ github.event_name == 'schedule' }}
        uses: tibdex/github-app-token@cdb5bfda87db263e4be5c6f570c4c39611ee952a # renovate: tag=v1.4.0
        with:
          app_id: ${{ secrets.PR_APP_ID }}
          private_key: ${{ secrets.PR_PRIVATE_KEY }}

      - name: Create Pull Request
        if: ${{ github.event_name == 'schedule' }}
        uses: peter-evans/create-pull-request@67df31e08a133c6a77008b89689677067fef169e # renovate: tag=v3.11.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: update-mold
          delete-branch: true
          title: 'Update mold'

  full:
    if: ${{ github.event_name != 'schedule' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Login to DockerHub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # renovate: tag=v1.10.0
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # renovate: tag=v1.6.0

      - name: Reload Docker buildx cache
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # renovate: tag=v2.1.6
        with:
          path: /tmp/.buildx-full-cache
          key: ${{ runner.os }}-buildx-full-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-full-
            ${{ runner.os }}-buildx-

      - name: Build (and, if a release, push to Docker Hub)
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229 # renovate: tag=v2.7.0
        with:
          context: .devcontainer
          tags: ${{ github.repository }}:1-bullseye
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-full-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-full-cache-new
          push: ${{ github.event_name == 'push' }}

      - name: Update cache
        run: |
          rm -rf /tmp/.buildx-full-cache
          mv /tmp/.buildx-full-cache{-new,}